language: python
python:
  - 3.6.5
notifications:
  email: false
install:
  - pip install --quiet -e .
  - export CORENLP_HOME=~/corenlp CORENLP_VERSION=stanford-corenlp-full-2018-10-05
  - export CORENLP_URL="http://nlp.stanford.edu/software/${CORENLP_VERSION}.zip"
  - wget $CORENLP_URL -O corenlp.zip
  - unzip corenlp.zip
  - mv $CORENLP_VERSION $CORENLP_HOME
  - mkdir ~/stanfordnlp_test
  - mkdir ~/stanfordnlp_test/in
  - mkdir ~/stanfordnlp_test/out
  - mkdir ~/stanfordnlp_test/scripts
  - cp tests/data/external_server.properties ~/stanfordnlp_test/scripts
  - export STANFORDNLP_TEST_HOME=~/stanfordnlp_test
script:
  - python -m pytest -m travis tests/
