language: python
python:
  - 3.6.5
notifications:
  email: false
install:
  - pip install --quiet -e .
  - export CORENLP_HOME=~/corenlp400 CORENLP_VERSION=stanford-corenlp-4.0.0
  - export CORENLP_URL="http://nlp.stanford.edu/software/${CORENLP_VERSION}.zip"
  - wget $CORENLP_URL -O corenlp400.zip
  - unzip corenlp400.zip
  - mv $CORENLP_VERSION $CORENLP_HOME
  - mkdir ~/stanza_test
  - mkdir ~/stanza_test/in
  - mkdir ~/stanza_test/out
  - mkdir ~/stanza_test/scripts
  - cp tests/data/external_server.properties ~/stanza_test/scripts
  - cp tests/data/example_french.json ~/stanza_test/out
  - export STANZA_TEST_HOME=~/stanza_test
script:
  - python -m pytest -m travis tests/
